<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AI-DATA DRIVEN</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d37b4cbf-fb54-4878-ac45-30253fa78dcd</testSuiteGuid>
   <testCaseLink>
      <guid>88d0d349-4219-4ba2-94d8-c3cfb27e65c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriven/DD_Article_Edit</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>33658dcc-1174-4fed-a961-978b37d68f3f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TD_Article</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>33658dcc-1174-4fed-a961-978b37d68f3f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>caseId</value>
         <variableId>var_caseId</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>33658dcc-1174-4fed-a961-978b37d68f3f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>title</value>
         <variableId>var_title</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>33658dcc-1174-4fed-a961-978b37d68f3f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>var_description</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>33658dcc-1174-4fed-a961-978b37d68f3f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>body</value>
         <variableId>var_body</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>33658dcc-1174-4fed-a961-978b37d68f3f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>tags</value>
         <variableId>var_tags</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>33658dcc-1174-4fed-a961-978b37d68f3f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dataType</value>
         <variableId>var_dataType</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>33658dcc-1174-4fed-a961-978b37d68f3f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>var_expectedResult</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>33658dcc-1174-4fed-a961-978b37d68f3f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>notes</value>
         <variableId>var_notes</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b120c8b0-5fc5-49c3-80d7-49bec77db950</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriven/DD_Create_Article</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f46341a1-3476-4e70-b90c-7e91a0f154a6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TD_Article</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f46341a1-3476-4e70-b90c-7e91a0f154a6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>caseId</value>
         <variableId>var_caseId</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f46341a1-3476-4e70-b90c-7e91a0f154a6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>title</value>
         <variableId>var_title</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f46341a1-3476-4e70-b90c-7e91a0f154a6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>var_description</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f46341a1-3476-4e70-b90c-7e91a0f154a6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>body</value>
         <variableId>var_body</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f46341a1-3476-4e70-b90c-7e91a0f154a6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>tags</value>
         <variableId>var_tags</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f46341a1-3476-4e70-b90c-7e91a0f154a6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dataType</value>
         <variableId>var_dataType</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f46341a1-3476-4e70-b90c-7e91a0f154a6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>var_expectedResult</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f46341a1-3476-4e70-b90c-7e91a0f154a6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>notes</value>
         <variableId>var_notes</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>86be14d0-328f-422f-a5f4-5220102ebcab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriven/DD_Edge_Security</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9f3eea89-3d0e-4b67-a8df-e90114b84e53</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TD_Edge_Security</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>9f3eea89-3d0e-4b67-a8df-e90114b84e53</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>caseId</value>
         <variableId>var_caseId</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9f3eea89-3d0e-4b67-a8df-e90114b84e53</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>var_module</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9f3eea89-3d0e-4b67-a8df-e90114b84e53</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>field</value>
         <variableId>var_field</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9f3eea89-3d0e-4b67-a8df-e90114b84e53</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>value</value>
         <variableId>var_value</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9f3eea89-3d0e-4b67-a8df-e90114b84e53</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dataType</value>
         <variableId>var_dataType</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9f3eea89-3d0e-4b67-a8df-e90114b84e53</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>var_expectedResult</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9f3eea89-3d0e-4b67-a8df-e90114b84e53</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>notes</value>
         <variableId>var_notes</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0179ec6-c2c7-46f1-a22f-e3e245eba729</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriven/DD_Add_Comment</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>29ee4a35-69f9-43b0-911a-eba148c1137a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TD_Comment</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>29ee4a35-69f9-43b0-911a-eba148c1137a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>caseId</value>
         <variableId>var_caseId</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>29ee4a35-69f9-43b0-911a-eba148c1137a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>commentBody</value>
         <variableId>var_commentBody</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>29ee4a35-69f9-43b0-911a-eba148c1137a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dataType</value>
         <variableId>var_dataType</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>29ee4a35-69f9-43b0-911a-eba148c1137a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>var_expectedResult</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>29ee4a35-69f9-43b0-911a-eba148c1137a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>notes</value>
         <variableId>var_notes</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76de9cdd-7b2c-4c20-b8a1-79efdd68c9a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriven/DD_Favorite_Article</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>69789780-1372-4a4d-85aa-33dcd550f51f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TD_Favorite</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>69789780-1372-4a4d-85aa-33dcd550f51f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>caseId</value>
         <variableId>var_caseId</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>69789780-1372-4a4d-85aa-33dcd550f51f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>action</value>
         <variableId>var_action</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>69789780-1372-4a4d-85aa-33dcd550f51f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dataType</value>
         <variableId>var_dataType</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>69789780-1372-4a4d-85aa-33dcd550f51f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>var_expectedResult</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>69789780-1372-4a4d-85aa-33dcd550f51f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>notes</value>
         <variableId>var_notes</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b36f9cd6-4772-4eed-8f52-00f372b58f9f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriven/DD_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>03cd0117-5709-4c66-9537-f6b4d0ce7527</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TD_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>03cd0117-5709-4c66-9537-f6b4d0ce7527</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>caseId</value>
         <variableId>var_caseId</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>03cd0117-5709-4c66-9537-f6b4d0ce7527</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>var_email</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>03cd0117-5709-4c66-9537-f6b4d0ce7527</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>var_password</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>03cd0117-5709-4c66-9537-f6b4d0ce7527</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dataType</value>
         <variableId>var_dataType</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>03cd0117-5709-4c66-9537-f6b4d0ce7527</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>var_expectedResult</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>03cd0117-5709-4c66-9537-f6b4d0ce7527</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>notes</value>
         <variableId>var_notes</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88fcd276-d700-4437-8db9-273935a5ca66</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriven/DD_Logout_Session</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d024eada-3f9d-4b77-98b8-a8282af1d07e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TD_Logout</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d024eada-3f9d-4b77-98b8-a8282af1d07e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>caseId</value>
         <variableId>var_caseId</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d024eada-3f9d-4b77-98b8-a8282af1d07e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>protectedRoute</value>
         <variableId>var_protectedRoute</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d024eada-3f9d-4b77-98b8-a8282af1d07e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dataType</value>
         <variableId>var_dataType</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d024eada-3f9d-4b77-98b8-a8282af1d07e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>var_expectedResult</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d024eada-3f9d-4b77-98b8-a8282af1d07e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>notes</value>
         <variableId>var_notes</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da71ee27-1f6c-47eb-aa48-19d81065e904</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description>Test case identifier from CSV</description>
         <id>var_caseId</id>
         <masked>false</masked>
         <name>caseId</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/DataDriven/DD_Register</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>09eabcb9-be4f-4485-9ecb-b79d7ef0dc3a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TD_Register</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>09eabcb9-be4f-4485-9ecb-b79d7ef0dc3a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>caseId</value>
         <variableId>var_caseId</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>09eabcb9-be4f-4485-9ecb-b79d7ef0dc3a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>var_username</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>09eabcb9-be4f-4485-9ecb-b79d7ef0dc3a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>var_email</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>09eabcb9-be4f-4485-9ecb-b79d7ef0dc3a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>var_password</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>09eabcb9-be4f-4485-9ecb-b79d7ef0dc3a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dataType</value>
         <variableId>var_dataType</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>09eabcb9-be4f-4485-9ecb-b79d7ef0dc3a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>var_expectedResult</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>09eabcb9-be4f-4485-9ecb-b79d7ef0dc3a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>notes</value>
         <variableId>var_notes</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39d3bd5b-1c6d-4c9f-a2d1-f87288d80374</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriven/DD_Register_Then_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bb565ff3-bdef-4ff2-8af1-efa5983d4e21</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TD_Register</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>bb565ff3-bdef-4ff2-8af1-efa5983d4e21</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>caseId</value>
         <variableId>var_caseId</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb565ff3-bdef-4ff2-8af1-efa5983d4e21</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>var_username</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb565ff3-bdef-4ff2-8af1-efa5983d4e21</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>var_email</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb565ff3-bdef-4ff2-8af1-efa5983d4e21</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>var_password</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb565ff3-bdef-4ff2-8af1-efa5983d4e21</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dataType</value>
         <variableId>var_dataType</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb565ff3-bdef-4ff2-8af1-efa5983d4e21</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>var_expectedResult</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb565ff3-bdef-4ff2-8af1-efa5983d4e21</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>notes</value>
         <variableId>var_notes</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe1c302b-363d-4e11-b554-1d0ced573d94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriven/DD_Update_Profile</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5f2c1015-a690-4189-9222-382ca6f0e0ed</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TD_Profile</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>5f2c1015-a690-4189-9222-382ca6f0e0ed</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>caseId</value>
         <variableId>var_caseId</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5f2c1015-a690-4189-9222-382ca6f0e0ed</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>var_username</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5f2c1015-a690-4189-9222-382ca6f0e0ed</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>bio</value>
         <variableId>var_bio</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5f2c1015-a690-4189-9222-382ca6f0e0ed</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>imageUrl</value>
         <variableId>var_imageUrl</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5f2c1015-a690-4189-9222-382ca6f0e0ed</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>var_email</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5f2c1015-a690-4189-9222-382ca6f0e0ed</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dataType</value>
         <variableId>var_dataType</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5f2c1015-a690-4189-9222-382ca6f0e0ed</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>var_expectedResult</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5f2c1015-a690-4189-9222-382ca6f0e0ed</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>notes</value>
         <variableId>var_notes</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
